### PR TITLE
Lib shuffle

### PR DESCRIPTION
**Pull request by Staars**
## Description:

Next try.

## Checklist:
  - [ ] The pull request is done against the latest development branch
  - [ ] Only relevant files were touched
  - [ ] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.5
  - [ ] The code change is tested and works with Tasmota core ESP32 V.2.0.14
  - [ ] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by Staars** [comment]
@benzino77

we would try to do some refactoring to reduce compile time for most environments.
This will probably interfere with Tasmocompiler but should not be too hard to resolve.

Do you see severe problems with these changes?

**Comment by benzino77** [comment]
It will definitely impact TasmoCompiler. I briefly looked through the contents (316 files changed!) and it shouldn't be super complicated to adjust TC for those changes. The changes which impact TasmoCompiler are in `platformio_tasmota_env.ini`, `platformio_tasmota_env32.ini` and `platformio.ini`. 
I think that proposed changes will hit the `development` version/branch of TasmoCompiler. The `production` one, should still work as expected as it is limited to the `v13.0.0`...`v13.3.0` version of Tasmota.

**Comment by Staars** [comment]
If you look at the file changes, this PR looks way more complicated than it is. We would only move a few folders and do the needed small changes in the ini files.

Anyway - we would ping you again, if this eventually goes to the main repo.

**Comment by benzino77** [comment]
Sounds like plan ;)

**Pull request closed without merging**
